# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeafcE9qUlPpjzLQMRH8IOunRC9cEUAn
"""
import streamlit as st
import pandas as pd
import re
import PyPDF2

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="AI Resume Screener",
    layout="wide"
)

# ---------------- FUNCTIONS ----------------
def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text.lower()

def extract_text_from_pdf(file):
    text = ""
    try:
        reader = PyPDF2.PdfReader(file)
        for page in reader.pages:
            if page.extract_text():
                text += page.extract_text()
    except:
        pass
    return text

def confidence_score(text):
    confidence_words = [
        "achieved", "improved", "led", "developed",
        "designed", "implemented", "managed", "optimized"
    ]
    score = sum(text.count(word) for word in confidence_words)
    return min(score * 10, 100)

def experience_score(text):
    experience_words = [
        "experience", "internship", "project",
        "worked", "employment", "responsible"
    ]
    score = sum(text.count(word) for word in experience_words)
    return min(score * 10, 100)

def verdict(score):
    if score >= 75:
        return "🌟 Highly Suitable"
    elif score >= 50:
        return "✅ Suitable"
    else:
        return "❌ Not Suitable"

# ---------------- UI ----------------
st.title("🤖 Intelligent Resume Screening System")
st.markdown("### AI-Based Resume Ranking, Suitability & Confidence Analysis")

col1, col2 = st.columns(2)

with col1:
    jd = st.text_area("📌 Step 1: Paste Job Description", height=300)

with col2:
    resumes = st.file_uploader(
        "📄 Step 2: Upload Resumes (PDF)",
        type="pdf",
        accept_multiple_files=True
    )

# ---------------- ANALYSIS ----------------
if st.button("🚀 Analyze & Rank Candidates"):
    if jd and resumes:
        with st.spinner("Analyzing resumes using AI..."):
            cleaned_jd = clean_text(jd)

            resume_texts = []
            resume_names = []

            for file in resumes:
                text = extract_text_from_pdf(file)
                if text:
                    resume_texts.append(clean_text(text))
                    resume_names.append(file.name)

            if resume_texts:
                # TF-IDF Vectorization
                vectorizer = TfidfVectorizer(stop_words="english")
                vectors = vectorizer.fit_transform([cleaned_jd] + resume_texts)

                # Similarity
                similarity_scores = cosine_similarity(
                    vectors[0:1], vectors[1:]
                ).flatten()

                results = []

                for i in range(len(resume_texts)):
                    conf = confidence_score(resume_texts[i])
                    exp = experience_score(resume_texts[i])
                    match = round(similarity_scores[i] * 100, 2)

                    final_score = round((match + conf + exp) / 3, 2)

                    results.append({
                        "Candidate Name": resume_names[i],
                        "JD Match (%)": match,
                        "Confidence Level": conf,
                        "Experience Level": exp,
                        "Final AI Score": final_score,
                        "Verdict": verdict(final_score)
                    })

                df = pd.DataFrame(results).sort_values(
                    by="Final AI Score", ascending=False
                )

                st.success("✅ Analysis Complete")
                st.dataframe(df, use_container_width=True)

            else:
                st.error("No readable resumes found.")
    else:
        st.warning("⚠️ Please provide both Job Description and Resumes.")
n and Resumes.")
