# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeafcE9qUlPpjzLQMRH8IOunRC9cEUAn
"""
import streamlit as st
import pandas as pd

import os


# ---------------- CONFIG ----------------
st.set_page_config(
    page_title="Intelligent Resume Screening System",
    layout="centered"
)

st.title("📄 Intelligent Resume Screening System")
st.subheader("Using NLP and Machine Learning")

DATA_PATH = "data/AI_Resume_Screening.csv"
MODEL_PATH = "model.pkl"
VECTORIZER_PATH = "vectorizer.pkl"

# ---------------- TRAIN MODEL ----------------
def train_model():
    

    # Combine text columns
    df["resume_text"] = (
        df["Skills"].fillna("") + " " +
        df["Education"].fillna("") + " " +
        df["Certifications"].fillna("") + " " +
        df["Job Role"].fillna("")
    )

    X = df["resume_text"]
    y = df["Recruiter Decision"]

    vectorizer = TfidfVectorizer(
        stop_words="english",
        max_features=4000
    )
    X_vec = vectorizer.fit_transform(X)

    model = LogisticRegression(max_iter=1000)
    model.fit(X_vec, y)

    joblib.dump(model, MODEL_PATH)
    joblib.dump(vectorizer, VECTORIZER_PATH)

    return model, vectorizer

# ---------------- LOAD MODEL ----------------
def load_model():
    
        

    model = joblib.load(MODEL_PATH)

    return model, vectorizer



# ---------------- USER INPUT ----------------
st.markdown("### 🔍 Enter Candidate Details")

skills = st.text_input("Skills (comma separated)")
education = st.selectbox(
    "Education",
    ["B.E","B.Sc", "B.Tech", "MBA", "M.Sc", "PhD"]
)
certifications = st.text_input("Certifications")
job_role = st.text_input("Job Role Applied For")

# ---------------- PREDICTION ----------------
if st.button("🚀 Screen Resume"):

    resume_text = (
        skills + " " +
        education + " " +
        certifications + " " +
        job_role
    )

    X = vectorizer.transform([resume_text])
    
    confidence = max(model.predict_proba(X)[0]) * 100

    st.markdown(f"## ✅ Decision: **{prediction}**")
    st.markdown(f"### 📊 Confidence Score: **{confidence:.2f}%**")

    if prediction == "Hire":
        st.success("Candidate is suitable for the role 🎯")
    else:
        st.error("Candidate does not meet the criteria ❌")
