# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeafcE9qUlPpjzLQMRH8IOunRC9cEUAn
"""
import streamlit as st



st.set_page_config(
    page_title="Intelligent Resume Screening System",
    layout="centered"
)

st.title("📄 Intelligent Resume Screening System")
st.subheader("Using NLP and Machine Learning")

model, vectorizer = load_model()

skills = st.text_input("Skills (comma separated)")
education = st.selectbox(
    "Education",
    ["B.Sc", "B.Tech", "MBA", "M.Sc", "PhD"]
)
certifications = st.text_input("Certifications")
job_role = st.text_input("Job Role Applied For")

# 👉 ONLY run prediction when button is clicked
if st.button("🚀 Screen Resume"):

    resume_text = (
        skills + " " +
        education + " " +
        certifications + " " +
        job_role
    )

    X = vectorizer.transform([resume_text])
    prediction = model.predict(X)[0]
    confidence = max(model.predict_proba(X)[0]) * 100

    st.markdown(f"## ✅ Decision: **{prediction}**")
    st.markdown(f"### 📊 Confidence Score: **{confidence:.2f}%**")

    if prediction == "Hire":
        st.success("Candidate is suitable for the role 🎯")
    else:
        st.error("Candidate does not meet the criteria ❌")

