# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeafcE9qUlPpjzLQMRH8IOunRC9cEUAn
"""
import streamlit as st

import PyPDF2

def extract_text_from_pdf(file):
    pdf_reader = PyPDF2.PdfReader(file)
    text = ""
    for page in pdf_reader.pages:
        text += page.extract_text()
    return text

st.title("Intelligent Resume Screener")

# Input: Job Description
jd_text = st.text_area("Paste the Job Description here:")

# Input: Resume Upload
uploaded_files = st.file_uploader("Upload Resumes (PDF)", type=["pdf"], accept_multiple_files=True)

if st.button("Analyze Resumes") and jd_text and uploaded_files:
    resumes_text = [extract_text_from_pdf(file) for file in uploaded_files]
    
    # Combine JD and Resumes for Vectorization
    all_content = [jd_text] + resumes_text
    
    # NLP: TF-IDF Vectorization
    vectorizer = TfidfVectorizer(stop_words='english')
    matrix = vectorizer.fit_transform(all_content)
    
    # Calculate Cosine Similarity
    scores = cosine_similarity(matrix[0:1], matrix[1:]).flatten()
    
    # Display Results
    st.subheader("Results")
    for i, score in enumerate(scores):
        st.write(f"**{uploaded_files[i].name}**: Match Score: {round(score * 100, 2)}%")
        st.progress(float(score))
